name: Bug report
description: Something is not working as expected
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill in as much detail as possible — reports with reproduction steps get fixed faster.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Exact steps to reproduce the behavior.
      placeholder: |
        1. Configure provider X
        2. Send message Y
        3. See error Z
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Spaceduck version
      description: Run `git log -1 --format='%h %s'` in the repo root
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (x64)
        - Linux (ARM64)
        - Windows (WSL2)
        - Other
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: Provider
      options:
        - LM Studio (local)
        - Gemini
        - OpenRouter
        - AWS Bedrock
        - Other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any relevant output from the terminal. Set `LOG_LEVEL=debug` in `.env` for verbose output.
      render: shell

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Anything else that might help — screenshots, config snippets, etc.
